export const CONSTANTS = {
  PLAYER_SPEED: 60,
  PLAYER_DASH_SPEED: 180,
  PLAYER_DASH_SPEED_DIAGONAL: 270,
  PLAYER_DASH_TIME: 160,
  PLAYER_DASH_RESET_TIME: 250,
  PLAYER_RESPAWN_TIME: 500,

  CONTROL_DASH: 'DASH',

  TILE_SIZE: 16,
};
